// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef MainFrame_h
#define MainFrame_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *mainwin;
#include <FL/Fl_Group.H>
extern Fl_Group *group_top;
#include <FL/Fl_Box.H>
extern Fl_Box *top_caption;
extern Fl_Box *toptime;
extern Fl_Box *topdate;
extern Fl_Group *group_bottom;
#include <FL/Fl_Button.H>
extern void bottom_eventinfo_cb(Fl_Button*, void*);
extern void bottom_setup_cb(Fl_Button*, void*);
extern void bottom_home_cb(Fl_Button*, void*);
extern void bottom_platformbc_cb(Fl_Button*, void*);
extern void bottom_service_cb(Fl_Button*, void*);
extern void bottom_net_cb(Fl_Button*, void*);
extern void bottom_presta_cb(Fl_Button*, void*);
extern void bottom_nextsta_cb(Fl_Button*, void*);
extern void bottom_platformbc_cb0(Fl_Button*, void*);
Fl_Double_Window* make_window();
#endif
