// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "MainFrame.h"

Fl_Double_Window *mainwin=(Fl_Double_Window *)0;

Fl_Group *group_top=(Fl_Group *)0;

Fl_Box *top_caption=(Fl_Box *)0;

Fl_Box *toptime=(Fl_Box *)0;

Fl_Box *topdate=(Fl_Box *)0;

Fl_Group *group_bottom=(Fl_Group *)0;

Fl_Double_Window* make_window() {
  { mainwin = new Fl_Double_Window(1024, 768);
    mainwin->color(FL_FOREGROUND_COLOR);
    mainwin->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
    { group_top = new Fl_Group(0, 0, 1024, 48);
      group_top->box(FL_FLAT_BOX);
      group_top->color((Fl_Color)48);
      { top_caption = new Fl_Box(354, 3, 316, 40, "CRRC ZELC Inteligent Network Department");
        top_caption->box(FL_FLAT_BOX);
        top_caption->color((Fl_Color)48);
        top_caption->labelsize(22);
        top_caption->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      } // Fl_Box* top_caption
      { toptime = new Fl_Box(901, 4, 99, 40, "08:08:08");
        toptime->box(FL_FLAT_BOX);
        toptime->color((Fl_Color)48);
        toptime->labelsize(21);
        toptime->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      } // Fl_Box* toptime
      { topdate = new Fl_Box(771, 4, 125, 40, "2008-08-08");
        topdate->box(FL_FLAT_BOX);
        topdate->color((Fl_Color)48);
        topdate->labelsize(21);
        topdate->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
      } // Fl_Box* topdate
      group_top->end();
    } // Fl_Group* group_top
    { group_bottom = new Fl_Group(0, 688, 1024, 79);
      group_bottom->color(FL_FOREGROUND_COLOR);
      group_bottom->align(Fl_Align(FL_ALIGN_CENTER));
      { Fl_Button* o = new Fl_Button(0, 692, 100, 75, "\344\272\213\344\273\266\n\344\277\241\346\201\257");
        o->down_box(FL_DOWN_BOX);
        o->selection_color((Fl_Color)186);
        o->labelsize(24);
        o->callback((Fl_Callback*)bottom_eventinfo_cb);
        o->type(FL_RADIO_BUTTON);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(102, 692, 100, 75, "\350\256\276 \347\275\256");
        o->down_box(FL_DOWN_BOX);
        o->selection_color((Fl_Color)226);
        o->labelsize(24);
        o->callback((Fl_Callback*)bottom_setup_cb);
        o->type(FL_RADIO_BUTTON);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(920, 692, 100, 75, "\344\270\273\351\241\265");
        o->box(FL_OVAL_BOX);
        o->down_box(FL_OVAL_BOX);
        o->labelsize(24);
        o->callback((Fl_Callback*)bottom_home_cb);
        o->type(FL_RADIO_BUTTON);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(612, 692, 100, 75, "\347\246\273\347\253\231\n\345\271\277\346\222\255");
        o->selection_color((Fl_Color)226);
        o->labelsize(24);
        o->callback((Fl_Callback*)bottom_platformbc_cb);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(204, 692, 100, 75, "\347\273\264 \346\212\244");
        o->selection_color((Fl_Color)226);
        o->labelsize(24);
        o->callback((Fl_Callback*)bottom_service_cb);
        o->type(FL_RADIO_BUTTON);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(306, 692, 100, 75, "\347\275\221\347\273\234\n\346\213\223\346\211\221");
        o->selection_color((Fl_Color)226);
        o->labelsize(24);
        o->callback((Fl_Callback*)bottom_net_cb);
        o->type(FL_RADIO_BUTTON);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(714, 692, 100, 75, "@+44>  S");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(24);
        o->callback((Fl_Callback*)bottom_presta_cb);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(816, 692, 100, 75, "S @+4>");
        o->down_box(FL_DOWN_BOX);
        o->selection_color((Fl_Color)226);
        o->labelsize(24);
        o->callback((Fl_Callback*)bottom_nextsta_cb);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(510, 692, 100, 75, "\350\277\233\347\253\231\n\345\271\277\346\222\255");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(24);
        o->callback((Fl_Callback*)bottom_platformbc_cb0);
      } // Fl_Button* o
      { new Fl_Button(408, 692, 100, 75);
      } // Fl_Button* o
      group_bottom->end();
    } // Fl_Group* group_bottom
    mainwin->clear_border();
    mainwin->end();
  } // Fl_Double_Window* mainwin
  return mainwin;
}
